### PR TITLE
feat: introduce a new workflow to verify build script on multi platforms 

### LINKED ISSUE #176: Add build test workflow
**Is your feature request related to a problem? Please describe.**
Add build test in workflow, ensure build steps in COMPILATION.md can work.

**Describe the solution you'd like**
Add a workflow file in .github/workflows

### PR DESCRIPTION
**Pull request by spencercjh**
CLOSE #176

### CODE REVIEW

**Comment by hengyoush** [comment]
Thanks for your contribution! 

Here are some suggestions I have:

1. I think we can add a workflow specifically for testing whether the build can be done on multiple platforms, while the current `test.yml` is mainly used for e2e tests.
2. Initially, we can add tests for Ubuntu only. The test environment should include multiple versions of Ubuntu and both ARM/AMD architectures(use the `matrix`). The main focus is to test whether `init_env.sh`  can complete the build. Other platforms like CentOS, Fedora, etc., can be added later.

**Comment by spencercjh** [comment]
> Thanks for your contribution!
> 
> Here are some suggestions I have:
> 
> 1. I think we can add a workflow specifically for testing whether the build can be done on multiple platforms, while the current `test.yml` is mainly used for e2e tests and it build kyanos on Ubuntu 22.04 only .
> 2. Initially, we can add tests for Ubuntu only. The test environment should include multiple versions of Ubuntu and both ARM/AMD architectures. The main focus is to test whether `init_env.sh`  can complete the build. Other platforms like CentOS, Fedora, etc., can be added later.
> 3. I think we can skip adding `go test` for now because many tests are currently broken and need to be fixed, which will take some time.
> 
> What do you think?

**Comment by spencercjh** [comment]
> Thanks for your contribution!
> 
> Here are some suggestions I have:
> 
> 1. I think we can add a workflow specifically for testing whether the build can be done on multiple platforms, while the current `test.yml` is mainly used for e2e tests and it build kyanos on Ubuntu 22.04 only .
> 2. Initially, we can add tests for Ubuntu only. The test environment should include multiple versions of Ubuntu and both ARM/AMD architectures (use matrix). The main focus is to test whether `init_env.sh`  can complete the build. Other platforms like CentOS, Fedora, etc., can be added later.
> 3. I think we can skip adding `go test` for now because many tests are currently broken and need to be fixed, which will take some time.
> 
> What do you think?

I attempted to implement your suggestions, but I found that the free version on GitHub (as opposed to the Team and Enterprise versions) does not support ARM64 runners: https://docs.github.com/en/actions/using-github-hosted-runners/using-larger - runners/about-larger-runners.

**Comment by spencercjh** [comment]
@hengyoush 

https://github.com/hengyoush/kyanos/blob/4be02272ecb7f9c86d0e4d5b79176189eae4b7d8/init_env.sh#L11-L30

The Ubuntu version here doesn't exactly match the Ubuntu version in the runner provided by GitHub. You need to open another PR to change it. I'm sorry that I don't really understand the constraints of these distro and CLANG versions. That's why the test for ubuntu-20.04 fails now.

**Comment by spencercjh** [comment]
To minimize the size of this PR, the workflow that governs the formatting and style of the code should be placed in a separate workflow yaml file.

**Comment by hengyoush** [comment]
Just add one check:
```shell
if [ ${release_num} == "20.04" ]; then
  CLANG_NUM=-10
```
I tested it on Ubuntu 20.04 and it works fine. @spencercjh

**Review by hengyoush — APPROVED** [review]

**Pull request merged**
